---
- name: Install web servers
  hosts: "{{target}}" # ip s2
  user: ubuntu
  tasks:
    - name: Add nodejs 16 repository
      shell: "curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -"

    - name: Install nodejs packages
      become: yes
      apt:
        pkg:
          - nodejs
          - nginx
        update_cache: yes
        state: latest

    - name: Create directories
      file:
        path: "/var/www"
        state: directory
        owner: 'ubuntu'
        group: 'ubuntu'
      become: yes

    - name: Clone project
      copy:
        dest: /var/www
        src: ../../srodowisko-wielokanalowej-platformy-komunikacyjnej

    - name: Rename directory
      command: mv /var/www/srodowisko-wielokanalowej-platformy-komunikacyjnej /var/www/webapp
